Downgrade ssb-ws back to 6.0.0
I thought that the "TypeError: next is not a function" but was resolved
in ssb-ws@6.2.0 but it looks like it still exists.

See: ssbc/ssb-ws#19

Note: this commit previously featured a deep update to secret-handshake
but it broke the build on Windows.

See: https://github.com/auditdrivencrypto/secret-handshake/issues/18